### ISSUE TITLE
CheckIsDnsRecord failed with wildcard & naked domain SANs certificate

### ISSUE THREAD

**Issue by gusuru** [shibayan/azure-keyvault-letsencrypt#14]
Added certificate `'{"Domains":["example.net","*.example.net"]}'` .
Logged `"The activity function 'CheckIsDnsRecord' failed: \"_acme-challenge.example.net value is not correct.\"."` .
Azure _acme-challenge.example.net TXT record contains 2 values, but CheckIsDnsRecord seems to check FirstOrDefault .

**Comment by shibayan** [comment]
@gusuru Thank you. I fixed this issue and released new version.
Please restart your function and retry it.
