### ISSUE TITLE
How to disable Read Only mode in Azure Function App

### ISSUE THREAD

**Issue by lfogaca43** [shibayan/azure-keyvault-letsencrypt#24]
694/5000
Hello Shibayan,

I have a question, please help me.
When I log in to AddCertificate_HttpStart the following message is displayed:
Your app is currently in read-only mode because you are running from a package file. When running from a package, the file system is read-only and no changes can be made to the files. To make any changes update the content in your zip file and WEBSITE_RUN_FROM_PACKAGE app setting.
I ran the command but did not run the Domain curl entry https://YOUR-FUNCTIONS.azurewebsites.net/api/AddCertificate_HttpStart?code=YOUR-FUNCTION-SECRET -X POST \
     -H 'Content-Type: application / json' \
     -d '{"Domains": ["example.com", "www.example.com"]}'
I followed the article https://stackoverflow.com/questions/53630773/how-to-disable-read-only-mode-in-azure-function-app but it did not work

Thanks for the help

**Comment by shibayan** [comment]
Please ignore the readonly display in Azure Portal as it has nothing to do with the behavior.
What is the error message when running AddCertificate_HttpStart?

**Comment by lfogaca43** [comment]
Hello,
I do not know if I am doing it correctly but here is the error:
![Error](https://user-images.githubusercontent.com/20261000/57087653-ead2de80-6cd6-11e9-89b6-385859c7107e.PNG)

**Comment by badamsdev** [comment]
@lfogaca43 your request body is wrong, only insert:
{"Domains":["example.com","www.example.com"]}

**Comment by lfogaca43** [comment]
Hi,
![AddCertificate](https://user-images.githubusercontent.com/20261000/57164469-94df6300-6dca-11e9-98d0-7f900aed66dc.PNG)
![ErrorGetcertificate](https://user-images.githubusercontent.com/20261000/57164470-94df6300-6dca-11e9-80fd-bea51f222535.PNG)



I follow your guidance but still continues with another mistake

Thanks a lot for the help

**Comment by shibayan** [comment]
Make sure that the key vault access policy is set correctly. Please try again later.

**Comment by lfogaca43** [comment]
Hello Shibayan,

Follow the
![Error2](https://user-images.githubusercontent.com/20261000/57234002-30085080-6ff6-11e9-87de-d0bc9fb8843e.PNG)
 print the key vault access policy, please let me know if I configured it correctly?

**Comment by shibayan** [comment]
The access policy settings are correct. As I'm updating the function app, please try again after restart function.

**Comment by lfogaca43** [comment]
Now it worked

Thanks Shibayan
