### ISSUE TITLE
'Dns01Authorization' failing.

### ISSUE THREAD

**Issue by mohirio** [shibayan/azure-keyvault-letsencrypt#33]
Hi,
Thank you for the great work.

I deployed the function but upon running it I'm getting this error 
```
"Orchestrator function 'IssueCertificate' failed: The activity function 'Dns01Authorization' failed
```

When trying to run ```AddCertificate_HttpStart```

Apparently there's a bad request somewhere but I can't define exactly where, investigating the response I found this.

```
The server encountered an error processing the request. The exception message is 'Object reference not set to an instance of an object.
```

I wonder if this is a bug or I'm doing something wrong.

Thanks again!

**Comment by ChristopherHaws** [comment]
I am having this issue as well. Looks like it has to do with changes made to `instanceId` being null here: https://github.com/shibayan/azure-keyvault-letsencrypt/blob/master/AzureKeyVault.LetsEncrypt/SharedFunctions.cs#L162

**Comment by shibayan** [comment]
@ChristopherHaws Thank you for investigate.
It is because you referred to ParentInstanceId according to your investigation.

@mohirio 
This problem has already been fixed and released. Please restart Function App and try again.
Thanks!

**Comment by mohirio** [comment]
@shibayan Wow thanks for the fast fix and thanks @ChristopherHaws for investigating! 
It's working perfectly now. I'll close this issue.
